// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/auth/join.ts";
import * as $3 from "./routes/auth/join.tsx";
import * as $4 from "./routes/auth/login.ts";
import * as $5 from "./routes/auth/login.tsx";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Join.tsx";
import * as $$2 from "./islands/Login.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/auth/join.ts": $2,
    "./routes/auth/join.tsx": $3,
    "./routes/auth/login.ts": $4,
    "./routes/auth/login.tsx": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Join.tsx": $$1,
    "./islands/Login.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
